// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://voydvjkvsathgckzcjgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZveWR2amt2c2F0aGdja3pjamdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNTczNzEsImV4cCI6MjA4OTgzMzM3MX0.tyDIUP5ZRyj0sG7KvS3e3TgyqT_2hzL11w91ln1wy7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});